### ISSUE TITLE
Tag filters don't work properly

### ISSUE THREAD

**Issue by Darxeal** [VirxEC/rlbot_gui_rust#2]
Some bots are in tabs which they shouldn't be
![image](https://user-images.githubusercontent.com/18472149/176146350-e3834404-6784-4767-a8f5-d204686848a4.png)

**Comment by VirxEC** [comment]
Great catch! I spend most of my time in the `All bots` tab and didn't notice. The issue was that I assumed `allowedTags` was an array when it was just a string, and an empty list of tags gets read as `[""]` - and a string with no characters is included in every other string.
